config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
    resources :posts do
      resources :comments
    end
    root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
 belongs_to :user
 has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		      redirect_to root_path
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author= comment.user.email
	.buttons
		= link_to "Edit", edit_post_comment_path(comment.post, comment)
		= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
 = f.input :comment 
 = f.submit

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@post, @comment]) do |f| 
 = f.input :comment
 = f.submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Github_clone
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	%link{ rel: "stylesheet", href: "http://fonts.googleapis.com/css?family=Lato:300,400,700", type: "text/css"}
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}/
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%header.main_header.clearfix
		.wrapper
			#logo
				%p= link_to "Github_clone", root_path
			#buttons
				- if user_signed_in?
					= link_to "New repository", new_post_path
					= link_to 'Sign out', destroy_user_session_path, :method => :delete
				- else
					= link_to "Sign Up", new_user_registration_path
					= link_to "Sign In", new_user_session_path
	.wrapper
		%p.notice= notice
		%p.alert= alert
	.wrapper
		= yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title
  = f.input :content
  = f.submit

app/views/posts/edit.html.haml
%h1 Edit Post
= render 'form'
=link_to "Cancel", post_path

app/views/posts/index.html.haml
#posts
 - @posts.each do |post|
  .post
   %h2.title= link_to post.title, post
   %p.date
    Published at
    = time_ago_in_words(post.created_at)
    = post.user.email

app/views/posts/new.html.haml
%h1 New request

= render 'form'

app/views/posts/show.html.haml
#post_content
	%h1= @post.title
	%p= @post.content

	#comments
		%h2
			= @post.comments.count
			Issues
		= render @post.comments

		%h3 Reply to repositary
		= render "comments/form"
-if user_signed_in?
	= link_to "Edit", edit_post_path(@post), class: "button"
	= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to do this?" }, class: "button";
- else